### ISSUE TITLE
Bug Report: i cant build the game 

### ISSUE THREAD

**Issue by ghost** [brightfyregit/agoti#3]
i was trying to build it and it gave me this error 

source/PlayState.hx:2150: characters 8-11 : Unknown identifier : lua 
 
can you please fix it please and thank you

**Comment by ghost** [comment]
and i am using mac

**Comment by kudorado** [comment]
Just comment out all error codes, that's simple to fix.

**Comment by ghost** [comment]
thats the only error

**Comment by ghost** [comment]
the rest its fine

**Comment by kudorado** [comment]
I mean remove the lines which cause the errors.

**Comment by ghost** [comment]
thats it thats all i have to do?

**Comment by ghost** [comment]
yooo thank you soo much

**Comment by ghost** [comment]
im an idiot im sorry lol

**Comment by kudorado** [comment]
NVM bro, glad that can help yo!
